name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/molspin-build-env:dockerenv

    steps:
    - uses: actions/checkout@v4
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
    - name: make
      run: make CC="ccache g++ -std=c++17" -j 16
    - uses: actions/upload-artifact@v4
      with:
        name: Molspin Executable
        path: molspin
    - name: Upload Artifact to release
      if: github.event_name == 'release'
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/octet-stream" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=molspin" \
          --data-binary "@molspin"

  deploy:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
      - name: Download Artifact
        shell: bash
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            $(curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
              ${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts | \
              python3 -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['archive_download_url'])") \
            -o molspin-artifact.zip
      - name: Unzip Artifact
        run: unzip -o molspin-artifact.zip
      - name: Copy Executable 
        run: cp molspin /data/lxd/viking_programs/molspin/molspin