name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/das0mann/molspin:dockerenv

    steps:
    - uses: actions/checkout@v4
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
    - name: make
      run: make CC="ccache g++ -std=c++17" ARMADILLO="-larmadillo -lopenblas -fopenmp -DARMA_NO_DEBUG" -j 16
    - uses: actions/upload-artifact@v4
      with:
        name: Molspin Executable
        path: molspin
